### ISSUE TITLE
zone property of GcsObject seems unnecessarily verbose

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/google-cloud-powershell#373]
e.g. Zone is listed as "https://www.googleapis.com/compute/v1/projects/csells-gcp-windows/zones/us-central1-f" for one of my objects, which makes it seem like I have my own set of zones. Shouldn't the zone just be "us-central1-f"? That's all I need to interact with an object on that zone, e.g. "Stop-GceInstance -Name  aspnet-1 -zone us-central1-f"

**Comment by chrsmith** [comment]
That is the value of the property as returned from the Cloud Storage API.

@quoctruong is this something we can apply a PowerShell custom formatter for? i.e. apply the result of a regular expression on the property of a specific .NET type before being printed to the shell?

**Comment by quoctruong** [comment]
@chrsmith Yes, I believe we can do something similar to [this](https://technet.microsoft.com/en-us/library/hh847881.aspx) (the part where they use ScriptBlock and Get-Date) to transform the property of a type.

**Comment by quoctruong** [comment]
This is fixed with https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/452.

**Comment by jpassing** [comment]
Issue still applies to `Get-GceInstance` (module version `1.0.1.10`): 
```
> Get-GceInstance |Where-Object {$_.Name -eq "temp-1"}|fl
CanIpForward      : False
CpuPlatform       : Unknown CPU Platform
...
Zone              : https://www.googleapis.com/compute/v1/projects/xxxx/zones/europe-west4-a
... ```

**Comment by quoctruong** [comment]
@jpassing This is behaving correctly. We are formatting the `zone` property to show the short version when you run `Get-GceInstance` but once you pipe that to `fl`, it will display the long version of the property.

**Comment by jpassing** [comment]
Makes sense -- however, it is still somewhat inconsistent considering that the long-form zone identifiers are not allowed as input to, say, `Get-GceInstance`.
